TaskFrontEnd/Controllers/DepartmentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskFrontEnd.Models;
using TaskFrontEnd.Repository.Irepository;

namespace TaskFrontEnd.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository _departmentRepository;
    
        public DepartmentController(IDepartmentRepository departmentRepository)
        {
            _departmentRepository = departmentRepository;
            
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            
            return Json(new { data = await _departmentRepository.GetAllAsync(StaticData.DepartmentApiPath)});
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Department department = new Department();
            if (id == null)
                return View(department);
            else
            {
                department = await _departmentRepository.GetAsync(StaticData.DepartmentApiPath, id.GetValueOrDefault());
                if (department == null)
                    return NotFound();
                return View(department);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Upsert(Department department)
        {
            if (ModelState.IsValid)
            {
                if (department.depId == 0)
                {
                    await _departmentRepository.CreateAsync(StaticData.DepartmentApiPath, department);
                }
                else
                {
                    await _departmentRepository.UpdateAsync(StaticData.DepartmentApiPath + department.depId, department);
                }
               return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(department);
            }
        }
        #region API Call
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
                return NotFound();
            var status = await _departmentRepository.DeleteAsync(StaticData.DepartmentApiPath, id);
            if (status)
                return Json(new { success = true, message = "data successfully deleted" });
            else
                return Json(new { success = false, message = "error while delete data" });
        }
        #endregion 
    }
}

TaskFrontEnd/Controllers/DesignationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TaskFrontEnd.Models;
using TaskFrontEnd.Repository;
using TaskFrontEnd.Repository.Irepository;

namespace TaskFrontEnd.Controllers
{
    public class DesignationController : Controller
    {
        private readonly IDesignationRepository _designationRepository;
        public DesignationController(IDesignationRepository designationRepository)
        {
            _designationRepository = designationRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _designationRepository.GetAllAsync(StaticData.DesignationApiPath)});
        }
        
        public async Task<IActionResult> Upsert(int? id)
        {
            Designation designation = new Designation();
            if (id == null)
                return View(designation);
            else
            {
                designation = await _designationRepository.GetAsync(StaticData.DesignationApiPath, id.GetValueOrDefault());
                if (designation == null)
                    return NotFound();
                return View(designation);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Upsert(Designation designation)
        {
             if (ModelState.IsValid)
            {
                if (designation.dsgId == 0)
                {
                    await _designationRepository.CreateAsync(StaticData.DesignationApiPath, designation);
                }
                else
                {
                    await _designationRepository.UpdateAsync(StaticData.DesignationApiPath +designation.dsgId, designation);
                }
                return RedirectToAction(nameof(Index));
            }                              
            else
            {
                return View(designation);
            }
        }
        #region API Call
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
                return NotFound();
            var status = await _designationRepository.DeleteAsync(StaticData.DesignationApiPath, id);
            if (status)
                return Json(new { success = true, message = "data successfully deleted" });
            else
                return Json(new { success = false, message = "error while delete data" });
        }
        #endregion 
    }
}

TaskFrontEnd/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nancy.Json;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using TaskFrontEnd.Models;
using TaskFrontEnd.Repository.Irepository;



namespace TaskFrontEnd.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeRepository _employeRepository;
        private readonly IDepartmentRepository _departmentRepository;
        private readonly IDesignationRepository _designationRepository;
        // private readonly IEmployeRepository _employeRepository;
        public EmployeeController(IEmployeRepository employeRepository, IDepartmentRepository departmentRepository, IDesignationRepository designationRepository)
        {
            _employeRepository = employeRepository;
            _departmentRepository = departmentRepository;
            _designationRepository = designationRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> GetAll()
        {
            return Json(new { data = await _employeRepository.GetAllAsync(StaticData.EmployeeApiPath)});
        }

        public async Task<IActionResult> Upsert(int? id)
        {
          var DesignationList = await _designationRepository.GetAllAsync(StaticData.DesignationApiPath);
          var Departmentlist = await _departmentRepository.GetAllAsync(StaticData.DepartmentApiPath);

            if (id == null)
            {
                EmployeeViewModel employevm = new EmployeeViewModel()
                {
                    Employee = new Employee(),
                    DepartmentList = Departmentlist.Select(cl => new SelectListItem()
                    {
                        Text = cl.dname,
                        Value = cl.depId.ToString()
                    }),
                    DesignationList = DesignationList.Select(cl => new SelectListItem()
                    {
                        Text = cl.dsgname,
                        Value = cl.dsgId.ToString()
                    }),

                };
                return View(employevm);
            }
            else
            {
                var employees = await _employeRepository.Getasync(StaticData.EmployeeApiPathGetByID, id.GetValueOrDefault());

                EmployeeViewModel employevm1 = new EmployeeViewModel()
                {
                    Employee = new Employee()
                    {
                        empId = employees[0].empId,
                        ename=employees[0].ename,
                        esal = employees[0].esal,
                        eadd= employees[0].eadd,
                        depId = employees[0].depId,
                        dname = employees[0].dname,
                       dsgId = employees[0].dsgId,
                       dsgname = employees[0].dsgname,
                                
                    },
                    DepartmentList = Departmentlist.Select(cl => new SelectListItem()
                    {
                        Text = cl.dname,
                        Value = cl.depId.ToString()
                    }),
                    DesignationList = DesignationList.Select(cl => new SelectListItem()
                    {
                        Text = cl.dsgname,
                        Value = cl.dsgId.ToString()
                    }),

                };

                if (employees == null)

                    return NotFound();
                return View(employevm1);
            }     
           
        }
        [HttpPost]
        public async Task<IActionResult> Upsert(Employee  employee)
        {

            if (ModelState.IsValid)
            {
                if (employee.empId == 0)
                {
                    await _employeRepository.CreateAsync(StaticData.EmployeeApiPath,employee);
                }
                else
                {
                    await _employeRepository.UpdateAsync(StaticData.EmployeeApiPath, employee);
                }
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(employee);
            }
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
                return NotFound();
           // var depid = _employeRepository.GetAsync(SD.EmployeeApiPathGetByID,id);
            var status = await _employeRepository.DeleteAsync(StaticData.EmployeeApiPath, id);
            if (status)
              return Json(new { success = true, message = "data successfully deleted" });
            else
               return Json(new { success = false, message = "error while delete data" });
        }
    }
}

TaskFrontEnd/Controllers/UserRegisterController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using TaskFrontEnd.Models;
using TaskFrontEnd.Models.ViewModel;
using TaskFrontEnd.Repository.Irepository;

namespace TaskFrontEnd.Controllers
{
    public class UserRegisterController : Controller
    {
        private readonly IUserRepository _userRepository;
       

        public UserRegisterController(IUserRepository userRepository)
        {
            _userRepository = userRepository;         
        }
        public IActionResult userRegister()=> View();
       
        [HttpPost]
        public async Task<IActionResult> userRegister(User user)
        {

            if (ModelState.IsValid)
            {
                await _userRepository.CreateUser(StaticData.UserRegister, user);
            }
            return RedirectToAction("userRegister");
                     
        }
        public IActionResult LoginUser()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> LoginUserAuthorized(authenticateViewModel authenticateViewModel)
        {          
            if (ModelState.IsValid)
            {
                using (var httpClient = new HttpClient())
                {
                    StringContent stringContent = new StringContent(JsonConvert.SerializeObject(authenticateViewModel), Encoding.UTF8, "application/json");
                    using (var result = await httpClient.PostAsync(StaticData.UserLogin, stringContent))
                    {

                        var UserDetails = await result.Content.ReadAsStringAsync();
                     
                        var Username = JsonConvert.DeserializeObject<User>(UserDetails);
                        string token = await result.Content.ReadAsStringAsync();
                        HttpContext.Session.SetString("JWToken", token);
                        HttpContext.Session.SetString(StaticData.newtoken, Username.Token);
                        HttpContext.Session.SetString(StaticData.UserDetails, Username.Username);
                        //CookieSet(SD.Cookiesdata, token, 10);
                        return RedirectToAction("LogIn");
                    }

                }
            }
            return Redirect("~/Home/Index");
           
        }
        public IActionResult LogIn()
        {
            return View();
        }
        //public void CookieSet(string key, string value, int? expireTime)
        //{
        //    CookieOptions option = new CookieOptions();
        //    if (expireTime.HasValue)
        //        option.Expires = DateTime.Now.AddMinutes(expireTime.Value);
        //    else
        //        option.Expires = DateTime.Now.AddMilliseconds(10);
        //    Response.Cookies.Append(key, value, option);
        //}
        //public void Remove(string key)
        //{
        //    Response.Cookies.Delete(SD.Cookiesdata);
        //}
    }
}

TaskFrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskFrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TaskFrontEnd</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
           
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Content Management
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-area="" asp-controller="Designation" asp-action="Index">Designation</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="btn-primary" asp-controller="UserRegister" asp-action="userRegister">Register</a>
                        </li>
                        &nbsp;
                        <li class="nav-item">
                            <a class="btn-primary" asp-controller="UserRegister" asp-action="LoginUser">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TaskFrontEnd - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://Kit.fontawesome.com/e19c476714.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>